#ifndef _PLAYER_ANIM_H_
#define _PLAYER_ANIM_H_

typedef enum
{
	PLAYER_CROUCH_IDLE,
	PLAYER_STAB,
	PLAYER_IDLE,
	PLAYER_RUNNING,
	PLAYER_ANIM_MAX
}PLAYER_ANIM_LIST;

#endif // !_PLAYER_ANIM_H_
